### ISSUE TITLE
dmesg unknown symbol

### ISSUE THREAD

**Issue by andig** [krumboeck/usb2can#10]
I've recently had to recompile the driver on raspbian with latest update. Loading the drivers gives this is dmesg though it seems to work fine:

	[ 1087.061677] usb_8dev: loading out-of-tree module taints kernel.
	[ 1087.061985] usb_8dev: Unknown symbol can_free_echo_skb (err 0)
	[ 1087.062012] usb_8dev: Unknown symbol can_put_echo_skb (err 0)
	[ 1087.062051] usb_8dev: Unknown symbol can_get_echo_skb (err 0)
	[ 1087.062119] usb_8dev: Unknown symbol open_candev (err 0)
	[ 1087.062164] usb_8dev: Unknown symbol alloc_can_skb (err 0)
	[ 1087.062229] usb_8dev: Unknown symbol free_candev (err 0)
	[ 1087.062288] usb_8dev: Unknown symbol close_candev (err 0)
	[ 1087.062331] usb_8dev: Unknown symbol can_bus_off (err 0)
	[ 1087.062366] usb_8dev: Unknown symbol alloc_candev (err 0)
	[ 1087.062399] usb_8dev: Unknown symbol alloc_can_err_skb (err 0)
	[ 1087.062432] usb_8dev: Unknown symbol register_candev (err 0)
	[ 1103.118811] usb_8dev: Unknown symbol can_free_echo_skb (err 0)
	[ 1103.118848] usb_8dev: Unknown symbol can_put_echo_skb (err 0)
	[ 1103.118890] usb_8dev: Unknown symbol can_get_echo_skb (err 0)
	[ 1103.118955] usb_8dev: Unknown symbol open_candev (err 0)
	[ 1103.119002] usb_8dev: Unknown symbol alloc_can_skb (err 0)
	[ 1103.119063] usb_8dev: Unknown symbol free_candev (err 0)
	[ 1103.119124] usb_8dev: Unknown symbol close_candev (err 0)
	[ 1103.119163] usb_8dev: Unknown symbol can_bus_off (err 0)
	[ 1103.119196] usb_8dev: Unknown symbol alloc_candev (err 0)
	[ 1103.119230] usb_8dev: Unknown symbol alloc_can_err_skb (err 0)
	[ 1103.119263] usb_8dev: Unknown symbol register_candev (err 0)
	[ 1325.406130] CAN device driver interface
	[ 1333.352104] usb_8dev 1-1.2.2:1.0 can0: firmware: 1.7, hardware: 1.0
	[ 1333.352433] usbcore: registered new interface driver usb_8dev

Anything to worry about?

**Comment by hartkopp** [comment]
At the time of the errors the can_dev module is not yet loaded.
The can_dev module is loaded at timestamp 1325.406130 - and then everything ist ok.
With "modprobe usb_8dev.ko" instead of "insmod usb_8dev.ko" the can_dev module is loaded as a required dependency in advance.
