### ISSUE TITLE
What would it take to port this to Mac OS X?

### ISSUE THREAD

**Issue by brandonros** [krumboeck/usb2can#11]

**Comment by krumboeck** [comment]
Sadly this is not portable. Because no other operating system supports [SocketCAN](https://en.wikipedia.org/wiki/SocketCAN) or something similar (AFAIK).

You have to write a driver from scratch or ask [UAB "8devices"](https://www.8devices.com/).

**Comment by brandonros** [comment]
Could we not just switch out the usb_bulk_write Linux commands for the Mac equivalent?

**Comment by krumboeck** [comment]
Sorry for the delay.

That's not that easy. The driver architecture for CAN is not standardized under Windows and MacOS. You can't simple take CAN hardware (and driver) from manufacturer A and use it with CAN software from manufacturer B.
That's the reason why so many CAN adapters speak LAWICEL protocol behind a serial interface.

**Comment by brandonros** [comment]
I wrote a WebUSB driver for the CandleLight gs_usb driver that works well under Mac.

**Comment by krumboeck** [comment]
That's a library not a driver. Of course you could add the usb2can commands to a device specific library.
